all: 
	g++ -std=c++11 main.cpp $(CPPFLAGS) httpquery.cpp -lcurl -ljsoncpp -lmongoclient -lboost_filesystem -lboost_program_options -lboost_system
	g++ -std=c++11 /home/ruslan/GitHub/GitApplications/HttpQuery/HttpQuery/ExchengeAnalyst/main.cpp $(CPPFLAGS) /home/ruslan/GitHub/GitApplications/HttpQuery/HttpQuery/ExchengeAnalyst/analyst.cpp -pthread -lmongoclient -lboost_filesystem -lboost_program_options -lboost_system -o tutorial
